'use strict';
const $=id=>document.getElementById(id); let csv='',result=null;
const api=async(path,body)=>{const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await response.json();if(!response.ok)throw Error(data.error||'请求失败');return data;};
function loaded(text,name){csv=text;$('filename').textContent=name;$('fileinfo').textContent=`${Math.max(0,text.trim().split(/\r?\n/).length-1)}行待校验，分析时检查字段与范围。`;$('analyze').disabled=false;$('error').textContent='';}
$('demo').onclick=async()=>{try{loaded(await(await fetch('/api/demo')).text(),'演示KPI · 自建合成数据');}catch(e){$('error').textContent=e.message;}};
$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;if(f.size>2_000_000){$('error').textContent='文件超过2MB';return;}loaded(await f.text(),f.name);};
$('analyze').onclick=async()=>{ $('analyze').disabled=true;$('progress').textContent='校验数据并运行模型…';$('error').textContent='';try{result=await api('/api/analyze',{csv_text:csv});render();$('progress').textContent='分析完成，点击记录查看证据。';}catch(e){$('error').textContent=e.message;$('progress').textContent='分析未完成，已保留上次结果。';}finally{$('analyze').disabled=false;}};
function render(){for(const id of ['results','assistant'])$(id).hidden=false;for(const k of ['samples','cells','abnormal','review'])$(k).textContent=result.summary[k];$('cell').replaceChildren(...result.cells.map(c=>new Option(c.cell_id,c.cell_id)));table();chart();$('mode').textContent='未配置API时使用离线证据汇总';$('answer').textContent='分析已完成，可以提问。';}
function table(){const rows=result.rows.map((r,i)=>({r,i})).filter(({r})=>!$('only').checked||r.diagnosis!=='正常');$('rows').replaceChildren();for(const {r,i} of rows.slice(0,300)){const tr=document.createElement('tr');const cells=[r.timestamp.replace('T',' ')+' / '+r.cell_id,r.diagnosis,r.prediction+' / '+(r.confidence*100).toFixed(1)+'%',r.needs_review?'需要':'常规复查',r.is_anomaly?'异常':'正常'];for(const t of cells){const td=document.createElement('td');td.textContent=t;tr.append(td);}tr.onclick=()=>{document.querySelectorAll('tr.selected').forEach(e=>e.classList.remove('selected'));tr.classList.add('selected');detail(result.rows[i]);};$('rows').append(tr);}$('rowcount').textContent=`符合筛选${rows.length}条，表格展示前${Math.min(300,rows.length)}条，导出文件包含全部记录。`;if(rows.length)detail(rows[0].r);else{$('detail').replaceChildren();const p=document.createElement('p');p.textContent='筛选范围内没有异常记录。';$('detail').append(p);}}
function add(parent,tag,text){const node=document.createElement(tag);node.textContent=text;parent.append(node);return node;}
function detail(r){const d=$('detail');d.replaceChildren();add(d,'h3',r.cell_id+' · '+r.diagnosis);add(d,'p',r.timestamp+'；模型候选 '+r.prediction+'；模型概率 '+(100*r.confidence).toFixed(1)+'%（未校准）');add(d,'h4','测量证据');const ul=add(d,'ul','');for(const e of r.evidence.length?r.evidence:['未触发启发式阈值；结合孤立森林与模型候选复核。'])add(ul,'li',e);for(const k of r.knowledge){add(d,'h4',`[${k.id}] ${k.cause}`);add(d,'p',k.explanation);const list=add(d,'ul','');k.actions.forEach(a=>add(list,'li',a));add(d,'p','复测指标：'+k.verification);}add(d,'p','建议仅作为人工排查参考。系统没有执行网络配置变更。');}
function chart(){if(!result)return;const canvas=$('chart'),w=canvas.clientWidth,h=250,dpr=window.devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const values=result.rows.filter(r=>r.cell_id===$('cell').value).sort((a,b)=>a.timestamp.localeCompare(b.timestamp)).map(r=>r[$('metric').value]);if(!values.length)return;const low=Math.floor(Math.min(...values)-3),high=Math.ceil(Math.max(...values)+3),x=i=>54+i/Math.max(1,values.length-1)*(w-80),y=v=>210-(v-low)/(high-low)*180;ctx.font='12px sans-serif';for(let i=0;i<=4;i++){const v=low+(high-low)*i/4;ctx.strokeStyle='#e2e9e9';ctx.beginPath();ctx.moveTo(50,y(v));ctx.lineTo(w-20,y(v));ctx.stroke();ctx.fillStyle='#627d83';ctx.fillText(v.toFixed(0),5,y(v)+4);}ctx.strokeStyle='#126b69';ctx.lineWidth=2;ctx.beginPath();values.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.stroke();ctx.fillStyle='#126b69';values.forEach((v,i)=>{ctx.beginPath();ctx.arc(x(i),y(v),3,0,Math.PI*2);ctx.fill();});ctx.fillStyle='#627d83';ctx.fillText('按时间排序的样本序号',54,242);ctx.fillText('1',50,226);ctx.fillText(String(values.length),w-34,226);}
$('cell').onchange=chart;$('metric').onchange=chart;window.onresize=chart;$('only').onchange=()=>result&&table();
function download(text,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('json').onclick=()=>result&&download(JSON.stringify(result,null,2),'wirelesscare-analysis.json','application/json');
$('download').onclick=async()=>{try{const r=await fetch('/api/report/'+result.id);if(!r.ok)throw Error('报告不存在或已过期');download(await r.text(),'wirelesscare-report.md','text/markdown');}catch(e){$('error').textContent=e.message;}};
$('chat').onsubmit=async e=>{e.preventDefault();const button=$('chat').querySelector('button');button.disabled=true;$('answer').textContent='正在整理证据…';try{const r=await api('/api/chat',{id:result.id,question:$('question').value});$('mode').textContent=r.mode;$('answer').textContent=r.answer;}catch(err){$('answer').textContent=err.message;}finally{button.disabled=false;}};
